<?php $this->partial('shared/header'); ?>

<div class="container">
    <div class="row">
        <div class="col-md-3">
            <?php $this->partial('me/setting/sidebar'); ?>
        </div>
        <?php $reff = $this->req->url; ?>
        <form class="col-md-9" method="post">
            <div class="page-header">
                <div class="pull-right">
                    <a href="<?= $next ?>" class="btn btn-default">Cancel</a>
                    <button class="btn btn-primary">Save</button>
                </div>
                <h3><?= $title ?></h3>
            </div>
            
            <div class="row">
                <div class="col-md-6">
                    <?= $this->form->field('page'); ?>
                    <?= $this->form->field('vendor'); ?>
                </div>
            </div>
        </form>
    </div>
</div>

<?php $this->partial('shared/footer'); ?>